#!/usr/bin/env bash
#Create a script that show 'bad and good luck' use if elif and else loop
l=1
while [ $l -le 10 ]
do
if [ $l -eq 4 ]
then
echo 'bad luck'
elif [ $l -eq 8 ]
then
echo 'good luck'
else
echo 'Best School'
fi
((l++))
done
