#!/usr/bin/env bash
#Create a script that use case loop
t=1
while [ $t -le 20 ]
do
echo $t
case $t in
4)
echo 'bad luck from China'
;;
9)
echo 'bad luck from Japan'
;;
17)
echo 'bad luck from Italy'
;;
esac
((t++))
done